// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bankify.proto

package grpc.bank.bankify;

public interface AccountTransferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.AccountTransfer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accountNumber = 1;</code>
   */
  int getAccountNumber();

  /**
   * <code>int32 pin = 2;</code>
   */
  int getPin();

  /**
   * <code>int32 toAccountNumber = 3;</code>
   */
  int getToAccountNumber();

  /**
   * <code>float value = 4;</code>
   */
  float getValue();
}
