// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bankify.proto

package grpc.bank.bankify;

public interface AccountDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.AccountData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accountNumber = 1;</code>
   */
  int getAccountNumber();

  /**
   * <code>int32 pin = 2;</code>
   */
  int getPin();
}
