// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankifySocial.proto

package grpc.bank.bankify;

public final class BankifySocialImpl {
  private BankifySocialImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_BankReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_BankReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_NewSocialUserData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_NewSocialUserData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023BankifySocial.proto\022\007bankify\"\034\n\tBankRe" +
      "ply\022\017\n\007message\030\001 \001(\t\"\225\001\n\021NewSocialUserDa" +
      "ta\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\022" +
      "\n\n\002id\030\003 \001(\t\022\016\n\006gender\030\004 \001(\t\022\r\n\005email\030\005 \001" +
      "(\t\022\020\n\010password\030\006 \001(\t\022\r\n\005phone\030\010 \001(\t\022\017\n\007a" +
      "ddress\030\t \001(\t2O\n\nBankSocial\022A\n\rAddSocialU" +
      "ser\022\032.bankify.NewSocialUserData\032\022.bankif" +
      "y.BankReply\"\000B(\n\021grpc.bank.bankifyB\021Bank" +
      "ifySocialImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bankify_BankReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bankify_BankReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_BankReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_bankify_NewSocialUserData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bankify_NewSocialUserData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_NewSocialUserData_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Id", "Gender", "Email", "Password", "Phone", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
