// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankifyPay.proto

package grpc.bank.bankify;

public final class BankifyPayImpl {
  private BankifyPayImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_LoginData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_LoginData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_LoginPayReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_LoginPayReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_LogoutData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_LogoutData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_PayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_PayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_PayHistory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_PayHistory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_PayReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_PayReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bankify_BankReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bankify_BankReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020BankifyPay.proto\022\007bankify\",\n\tLoginData" +
      "\022\r\n\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"O\n\rLog" +
      "inPayReply\022\024\n\014LoginMessage\030\001 \001(\t\022\021\n\tFirs" +
      "tName\030\002 \001(\t\022\025\n\raccountNumber\030\003 \001(\005\"\033\n\nLo" +
      "goutData\022\r\n\005email\030\001 \001(\t\"O\n\nPayRequest\022\022\n" +
      "\ncardNumber\030\001 \001(\t\022\013\n\003pin\030\002 \001(\005\022\021\n\tholder" +
      "Acc\030\003 \001(\005\022\r\n\005value\030\004 \001(\002\"P\n\nPayHistory\022\022" +
      "\n\ncardNumber\030\001 \001(\t\022\021\n\tholderAcc\030\002 \001(\005\022\r\n" +
      "\005value\030\003 \001(\002\022\014\n\004date\030\004 \001(\t\"F\n\010PayReply\022\017" +
      "\n\007details\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005value\030\003" +
      " \001(\002\022\014\n\004date\030\004 \001(\t\"\034\n\tBankReply\022\017\n\007messa" +
      "ge\030\001 \001(\t2\363\001\n\007BankPay\022;\n\013HolderLogin\022\022.ba" +
      "nkify.LoginData\032\026.bankify.LoginPayReply\"" +
      "\000\0227\n\nUserLogout\022\023.bankify.LogoutData\032\022.b" +
      "ankify.BankReply\"\000\022/\n\003Pay\022\023.bankify.PayR" +
      "equest\032\021.bankify.PayReply\"\000\022A\n\022PayHistor" +
      "yRegister\022\023.bankify.PayHistory\032\022.bankify" +
      ".BankReply\"\000(\001B%\n\021grpc.bank.bankifyB\016Ban" +
      "kifyPayImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bankify_LoginData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bankify_LoginData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_LoginData_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_bankify_LoginPayReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bankify_LoginPayReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_LoginPayReply_descriptor,
        new java.lang.String[] { "LoginMessage", "FirstName", "AccountNumber", });
    internal_static_bankify_LogoutData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bankify_LogoutData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_LogoutData_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_bankify_PayRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bankify_PayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_PayRequest_descriptor,
        new java.lang.String[] { "CardNumber", "Pin", "HolderAcc", "Value", });
    internal_static_bankify_PayHistory_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bankify_PayHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_PayHistory_descriptor,
        new java.lang.String[] { "CardNumber", "HolderAcc", "Value", "Date", });
    internal_static_bankify_PayReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bankify_PayReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_PayReply_descriptor,
        new java.lang.String[] { "Details", "Name", "Value", "Date", });
    internal_static_bankify_BankReply_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_bankify_BankReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bankify_BankReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
