// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankifyPay.proto

package grpc.bank.bankify;

public interface LoginDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.LoginData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
