// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bankify.proto

package grpc.bank.bankify;

public interface LoginReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.LoginReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string LoginMessage = 1;</code>
   */
  java.lang.String getLoginMessage();
  /**
   * <code>string LoginMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginMessageBytes();

  /**
   * <code>string FirstName = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string FirstName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>int32 accountNumber = 4;</code>
   */
  int getAccountNumber();
}
