// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bankify.proto

package grpc.bank.bankify;

public interface MovementDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.MovementData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string movement = 1;</code>
   */
  java.lang.String getMovement();
  /**
   * <code>string movement = 1;</code>
   */
  com.google.protobuf.ByteString
      getMovementBytes();
}
