// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bankify.proto

package grpc.bank.bankify;

public interface NewUserDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.NewUserData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string id = 3;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 3;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string gender = 4;</code>
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 4;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string email = 5;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 5;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 6;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 6;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int32 pin = 7;</code>
   */
  int getPin();

  /**
   * <code>string phone = 8;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 8;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string address = 9;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 9;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
