// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankifyPay.proto

package grpc.bank.bankify;

public interface PayHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.PayHistory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cardNumber = 1;</code>
   */
  java.lang.String getCardNumber();
  /**
   * <code>string cardNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();

  /**
   * <code>int32 holderAcc = 2;</code>
   */
  int getHolderAcc();

  /**
   * <code>float value = 3;</code>
   */
  float getValue();

  /**
   * <code>string date = 4;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 4;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
