// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankifyPay.proto

package grpc.bank.bankify;

public interface PayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.PayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cardNumber = 1;</code>
   */
  java.lang.String getCardNumber();
  /**
   * <code>string cardNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();

  /**
   * <code>int32 pin = 2;</code>
   */
  int getPin();

  /**
   * <code>int32 holderAcc = 3;</code>
   */
  int getHolderAcc();

  /**
   * <code>float value = 4;</code>
   */
  float getValue();
}
