// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankifyPay.proto

package grpc.bank.bankify;

public interface PayReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bankify.PayReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string details = 1;</code>
   */
  java.lang.String getDetails();
  /**
   * <code>string details = 1;</code>
   */
  com.google.protobuf.ByteString
      getDetailsBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>float value = 3;</code>
   */
  float getValue();

  /**
   * <code>string date = 4;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 4;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
